/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("java")
    application
    id("checkstyle")
    // other plugins
}

checkstyle {
    toolVersion = "11.0.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.guava:guava:32.1.2-jre")
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("com.github.stefanbirkner:system-lambda:1.2.1")
}

application {
    mainClass.set("ui.Nuke") // fully qualified class name
    applicationDefaultJvmArgs = listOf("-Dfile.encoding=UTF-8")
}
tasks.jar {
    archiveFileName.set("NUCLEAR.jar") // custom name
    destinationDirectory.set(project.rootDir) // custom folder
    manifest {
        attributes["Main-Class"] = "ui.Nuke"
    }
}
tasks.test {
    useJUnitPlatform()

    testLogging {
        events("passed", "skipped", "failed")

        showExceptions = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showCauses = true
        showStackTraces = true
        showStandardStreams = false
    }
}

