/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */
val javaFxVersion = "17.0.7"
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
plugins {
    id("java")
    application
    id("checkstyle")
    id("io.github.goooler.shadow") version "8.1.8"
}

checkstyle {
    toolVersion = "11.0.0"
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven { url = uri("https://raw.githubusercontent.com/DFKI-MLT/Maven-Repository/main") }
        }
        filter { includeGroup("de.dfki.lt.jtok") }
    }
}

dependencies {
    implementation("com.google.guava:guava:32.1.2-jre")

    implementation("org.openjfx:javafx-base:$javaFxVersion:win")
    implementation("org.openjfx:javafx-base:$javaFxVersion:mac")
    implementation("org.openjfx:javafx-base:$javaFxVersion:linux")

    implementation("org.openjfx:javafx-controls:$javaFxVersion:win")
    implementation("org.openjfx:javafx-controls:$javaFxVersion:mac")
    implementation("org.openjfx:javafx-controls:$javaFxVersion:linux")

    implementation("org.openjfx:javafx-fxml:$javaFxVersion:win")
    implementation("org.openjfx:javafx-fxml:$javaFxVersion:mac")
    implementation("org.openjfx:javafx-fxml:$javaFxVersion:linux")

    implementation("org.openjfx:javafx-graphics:$javaFxVersion:win")
    implementation("org.openjfx:javafx-graphics:$javaFxVersion:mac")
    implementation("org.openjfx:javafx-graphics:$javaFxVersion:linux")

    implementation("com.github.stefanbirkner:system-lambda:1.2.1")
    
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("com.github.stefanbirkner:system-lambda:1.2.1")

}

application {
    mainClass.set("ui.Launcher") // fully qualified class name
    applicationDefaultJvmArgs = listOf(
        "-Dfile.encoding=UTF-8",
        "-Djavax.sound.sampled.SourceDataLine=#REALTEK HD AUDIO 2ND OUTPUT"
    )
}
tasks.jar {
    archiveFileName.set("NUCLEAR.jar")
    destinationDirectory.set(project.rootDir)
    manifest {
        attributes["Main-Class"] = "ui.Launcher"
    }
    from(sourceSets.main.get().output)
    from({
        configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }
    })
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from({
        configurations.runtimeClasspath.get().map { 
            if (it.isDirectory) it else zipTree(it) 
        }
    })
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    // FreeTTS needs this manifest entry to find voices inside the jar
    manifest {
        attributes["Main-Class"] = "ui.Launcher"
        attributes["Class-Path"] = configurations.runtimeClasspath.get()
            .joinToString(" ") { it.name }
    }
}

tasks.test {
    useJUnitPlatform()

    testLogging {
        events("passed", "skipped", "failed")

        showExceptions = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showCauses = true
        showStackTraces = true
        showStandardStreams = false
    }
}
tasks.register<Zip>("releaseZip") {
    archiveFileName.set("NUCLEAR.zip")
    destinationDirectory.set(project.rootDir)
    from(tasks.jar) // include the jar
    from("config") { into("config") } // include config folder
    from("data") { into("data") } // include save folder if needed
}
