name: Build eSpeak Binaries
on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install eSpeak NG
        run: sudo apt install -y espeak-ng

      - name: Copy binaries
        run: |
          cp /usr/bin/espeak-ng ./espeak-linux
          cp -r /usr/lib/x86_64-linux-gnu/espeak-ng-data ./espeak-ng-data-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: espeak-linux
          path: |
            espeak-linux
            espeak-ng-data-linux/

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Install eSpeak NG
        run: brew install espeak-ng

      - name: Copy binaries
        run: |
          cp $(which espeak-ng) ./espeak-mac
          cp -r $(brew --prefix)/lib/espeak-ng-data ./espeak-ng-data-mac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: espeak-mac
          path: |
            espeak-mac
            espeak-ng-data-mac/